server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: liquibase
    password: 123456aA@
    url: jdbc:postgresql://localhost:5432/liquibase
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/change-log-root.xml
